---
title: "HITECH_Act_Case"
author: "Karl Grindal"
date: "6/19/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("dplyr")

```


```{r}
# Case 1: HITECH Security Law

# Enacted: February 17, 2009
# Enforcement: May 27, 2009

setwd<-("C:/Users/karl_000/Documents/SpiderOak Hive/Dissertation/Dissertation_BreachesDataset")

AllStateClean <- read.table(file="AllStateClean.txt", sep=";")

AllStateClean$firstdate <- substr(AllStateClean$reported_date, start=1, stop=10) # Use this string for Massachusetts v New Hampshire

HITECH1 <- subset(AllStateClean, AllStateClean$year == 2005)
HITECH2 <- subset(AllStateClean, AllStateClean$year == 2006)
HITECH3 <- subset(AllStateClean, AllStateClean$year == 2007)
HITECH4 <- subset(AllStateClean, AllStateClean$year == 2008)
HITECH5 <- subset(AllStateClean, AllStateClean$year == 2009)
HITECH6 <- subset(AllStateClean, AllStateClean$year == 2010)

HITECH <- rbind(HITECH1, HITECH2, HITECH3, HITECH4, HITECH5, HITECH6)

write.csv(HITECH, "HITECH.csv")

```


```{r}

HITECH <- read.csv("HITECH.csv")
DUNS <- read.csv("DUNS_HITECH.csv")
                 
NAICS <- merge(HITECH, DUNS, by="clean_name", all=TRUE)

NAICS$DUNS_2 <- substr(NAICS$Primary.NAICS.Code, start=1, stop=2)
colSums(!is.na(NAICS)) # 1741 
colSums(is.na(NAICS)) # 215
1741/1956 # = 89%

write.csv(NAICS, "NAICS_Clean.csv")

Health <- NAICS[grepl( "62", NAICS$DUNS_2), ]
Finance <- NAICS[grepl( "52", NAICS$DUNS_2), ]
Education <- NAICS[grepl( "61", NAICS$DUNS_2), ]
Information <- NAICS[grepl( "51", NAICS$DUNS_2), ]

Non_Health <- NAICS %>%
                   filter(DUNS_2 != 62)   


```

```{r}
pop <- read.csv("populations.csv")
pop <- pop[c(12,20,22,30,42),-c(2:101)] # Hawaii row 12, Maine row 2, Massachusetts row 22, New Hampshire row 30, North Carolina row 34
pop <- pop[,1:17] # removing the last available month to match length
pop <- t(as.data.frame(pop))
pop

treatment_start <- as.Date("02/17/2009", "%m/%d/%Y") # Legislation H.B. 4144 becomes effective
treatment_end <- as.Date("05/27/2009", "%m/%d/%Y")+30 # moving avg uses 30 days post treatment

colnames(pop) <- pop[1,]
pop <- pop[-1,]
rownames(pop) <- seq(1:nrow(pop))

# Creating blank frequency starting with earliest date

dat <- data.frame(seq(as.Date("2005-01-01"), by="1 month", 
                      length.out=72)) # treatment date

names(dat) <- "yearmonth"
dat <- format(dat,  "%Y/%m")
dat
```


```{r}
# Create control and treatment populations


NAICS$firstdate <- substr(NAICS$reported_date, start=1, stop=10) # Use this string for Massachusetts v New Hampshire

# Format control dates into months

NAICS$date_formatted <- format(as.Date(NAICS$firstdate, "%Y-%m-%d"), "%Y/%m") # Alternative is "%m/%d/%Y"
NAICS_ts <- NAICS %>% 
  dplyr::group_by(NAICS$date_formatted) %>% 
  dplyr::summarise(frequency = n())

names(NAICS_ts)[1] <- "yearmonth"
NAICS_ts <- merge(NAICS_ts, dat, by="yearmonth", all=TRUE)
NAICS_ts$frequency[is.na(NAICS_ts$frequency)]<-0
NAICS_ts

# Look at Raw Frequency Counts

NAICS_ts <- ts(NAICS_ts$frequency, frequency = 12, start = c(2005,1))

ts.plot(NAICS_ts, main = "Breaches over time", xlim=c(2005,2011), gpars = list(col = c("black", "red")), xlab = "Years", ylab = "Count per month")

```


```{r}
# Create control and treatment populations
treatment <-  Health
control <-  Non_Health

treatment$firstdate <- substr(treatment$reported_date, start=1, stop=10) # Use this string for Massachusetts v New Hampshire
control$firstdate <- substr(control$reported_date, start=1, stop=10) # Use this string for Massachusetts v New Hampshire


# Format control dates into months

treatment$date_formatted <- format(as.Date(treatment$firstdate, "%Y-%m-%d"), "%Y/%m") # Alternative is "%m/%d/%Y"
treatment_ts <- treatment %>% 
  dplyr::group_by(treatment$date_formatted) %>% 
  dplyr::summarise(frequency = n())

names(treatment_ts)[1] <- "yearmonth"
treatment_ts <- merge(treatment_ts, dat, by="yearmonth", all=TRUE)
treatment_ts$frequency[is.na(treatment_ts$frequency)]<-0
treatment_ts

# Format treatment dates into months
control$date_formatted <- format(as.Date(control$firstdate, 
                                         "%Y-%m-%d"), "%Y/%m") # Alternative is "%m/%d/%Y"
control_ts <- control %>% 
  dplyr::group_by(control$date_formatted) %>% 
  dplyr::summarise(frequency = n())

names(control_ts)[1] <- "yearmonth"
control_ts <- merge(control_ts, dat, by="yearmonth", all=TRUE)
control_ts
# control_ts <- control_ts[1:36,] 
control_ts$frequency[is.na(control_ts$frequency)]<-0

comb_ts <- merge(treatment_ts, control_ts, by="yearmonth", all=TRUE) # please make sure the length of both your timeseries
comb_ts

# Look at Targeted Frequency Count

treatment_tsM <- ts(treatment_ts, frequency = 12, 
                   start = c(2008,06))
control_tsM <- ts(control_ts$frequency, frequency = 12, start = 
                   c(2008,06))

# Look at Raw Frequency Counts

treatment_ts <- ts(treatment_ts$frequency, frequency = 12, 
                   start = c(2005,1))
control_ts <- ts(control_ts$frequency, frequency = 12, start = 
                   c(2005,1))


ts.plot(control_ts, treatment_ts, main = "Breaches over time", xlim=c(2005,2011), gpars = list(col = c("black", "red")), xlab = "Years", ylab = "Count per month")

ts.plot(control_ts, treatment_ts, main = "Breaches over time", xlim=c(2008.5,2011), gpars = list(col = c("black", "red")), type = "b", xlab = "Years", ylab = "Count per month")

```


```{r}

# command to decompose the control
controltimeseriescomponents <- decompose(control_ts)
controltimeseriescomponents
plot(controltimeseriescomponents)

controltimeseriesseasonallyadjusted <- control_ts - controltimeseriescomponents$seasonal

plot(controltimeseriesseasonallyadjusted)


# source of statistical tests http://r-statistics.co/Time-Series-Analysis-With-R.html

acfcontrol <- acf(control_ts) # autocorrelation (i.e. a Time Series with lags of itself)
# shows that the control time series is a "stationary time series"

pacfcontrol <- pacf(control_ts)  # partial autocorrelation (i.e. correlation of the time series with a lag of itself, with the linear dependence of all the lags between them removed.)

ccfRes <- ccf(control_ts, treatment_ts, ylab = "cross-correlation")

# adf test is an Augmented Dickey-Fuller Test
adf.test(control_ts) # p-value < 0.05 indicates the TS is stationary
kpss.test(control_ts) # Kwiatkowski-Phillips-Schmidt-Shin (KPSS) test



```


```{r}
# ITS analyses use regression-based techniques

# Added dummy variables for ITS
control <- as.data.frame(t(rbind(comb_ts$yearmonth,comb_ts$frequency.x)))
control$treat <- as.vector(rep(0,nrow(control)))                  # Create example vector
time <- 1:nrow(control)
control$time <- as.vector(time)
control$z <- c(rep(0,49),1:(nrow(control)-49))

treatment <- as.data.frame(t(rbind(comb_ts$yearmonth,comb_ts$frequency.y)))
treatment$treat <- as.vector(rep(1,nrow(control)))                  # Create example vector
time <- 1:nrow(control)
treatment$time <- as.vector(time)
treatment$z <- c(rep(0,49),1:(nrow(control)-49))

AppendITS <- rbind(treatment,control)
AppendITS
names(AppendITS) <- c("yearmonth","incident_permil","treat","time","z")
AppendITS$incident_permil <- as.numeric(as.character(AppendITS$incident_permil))
AppendITS$time <- as.numeric(as.character(AppendITS$time))
AppendITS$z <- as.numeric(as.character(AppendITS$z))

# https://www.sas.com/content/dam/SAS/en_ca/User%20Group%20Presentations/Health-User-Groups/ITS_SAS.pdf


sapply(AppendITS, class)


regTest <- lm(incident_permil ~ time + treat + z, AppendITS) 
summary(regTest)

regTest2 <- lm(incident_permil ~ time + treat + time*treat + z + z*time + z*treat + z*treat*time, AppendITS) 
summary(regTest2)

AppendITS

```



```{r}

# Identifying relevant dates

# HIGH TECH Act regulations become effective on February 17, 2009
# Enforcement of HIGH TECH Act implement on May 27, 2009

treatment_start <- as.Date("02/17/2009", "%m/%d/%Y") # Legislation H.B. 4144 becomes effective
treatment_end <- as.Date("05/27/2009", "%m/%d/%Y")+30 # moving avg uses 30 days post treatment


treatment_ts
control_ts

comb_ts <- merge(treatment_ts, control_ts, by="yearmonth")
names(comb_ts) <- c("yearmonth","Treatment","Control","Massachusetts","New Hamsphire", "North Carolina","Treatment_per_Mil", "Control_per_Mil")
comb_ts$match <- as.character(comb_ts$yearmonth)

treatment_start<- format(as.Date(as.character(treatment_start), origin = "1970-01-01"), "%Y/%m")
pretreat <- comb_ts[(which(comb_ts$match==treatment_start)-5):which(comb_ts$match==treatment_start),]
pretreat$type <- "pretest"

treatment_end<- format(as.Date(as.character(treatment_end), origin = "1970-01-01"), "%Y/%m")
posttreat <- comb_ts[which(comb_ts$match==treatment_end):(which(comb_ts$match==treatment_end)+5),]
posttreat$type <- "posttest"

mean(posttreat$Treatment) - mean(pretreat$Treatment)
mean(posttreat$Control) - mean(pretreat$Control)

treatment_range <- comb_ts[(which(comb_ts$match==treatment_start)+1):(which(comb_ts$match==treatment_end)-1),]
treatment_range$type <- "test"

experiment <- rbind(pretreat,treatment_range,posttreat)
experiment$Treatment[is.na(experiment$Treatment)]<-0
experiment$Control[is.na(experiment$Control)]<-0

ts.plot(experiment$Treatment, col = "red")
ts.plot(experiment$Control, col = "blue")

# Look at Raw Frequency Counts

treatment_ts <- ts(experiment$Treatment, frequency = 12, start = c(2008,4))
control_ts <- ts(experiment$Control, frequency = 12, start = c(2008,4))
ts.plot(control_ts, treatment_ts, main = "Breaches over time", xlim=c(2008,2011), gpars = list(col = c("black", "red")), xlab = "Years", ylab = "Count per month")

# Look at Treatment and Control per Million

treatment_tsM <- ts(experiment$Treatment_per_Mil, frequency = 12, start = c(2008,4))
treatment_tsM

control_tsM <- ts(experiment$Control_per_Mil, frequency = 12, start = c(2008,4))
control_tsM

ts.plot(control_tsM, treatment_tsM, main = "Breaches over time", xlim=c(2008,2011), gpars = list(col = c("black", "red")), type = "b", xlab = "Years", ylab = "Count per month")

```



```{r}

# ITS analyses use regression-based techniques

experiment2 <- experiment[experiment$type != "test",]
experiment2

# Added dummy variables for ITS
control <- as.data.frame(t(rbind(experiment2$yearmonth,experiment2$Control_per_Mil)))
control$treat <- as.vector(rep(0,nrow(control)))                  # Create example vector
time <- 1:nrow(control)
control$time <- as.vector(time)
control$z <- c(rep(0,6),1:(nrow(control)-6))

treatment <- as.data.frame(t(rbind(experiment2$yearmonth,experiment2$Treatment_per_Mil)))
treatment$treat <- as.vector(rep(1,nrow(control)))                  # Create example vector
time <- 1:nrow(control)
treatment$time <- as.vector(time)
treatment$z <- c(rep(0,6),1:(nrow(control)-6))

AppendITS <- rbind(treatment,control)

names(AppendITS) <- c("yearmonth","incident_permil","treat","time","z")
AppendITS$incident_permil <- as.numeric(as.character(AppendITS$incident_permil))
AppendITS$time <- as.numeric(as.character(AppendITS$time))
AppendITS$z <- as.numeric(as.character(AppendITS$z))


factor_cols <- c("treat","time","z")

sapply(AppendITS, class)

regTest <- lm(incident_permil ~ time + treat + z, AppendITS) 
summary(regTest)

regTest2 <- lm(incident_permil ~ time + treat + time*treat + z + z*time + z*treat + z*treat*time, AppendITS) 
summary(regTest2)

View(AppendITS)

```



```{r}
# Looking into state headquarters
Headquarter <- subset(NAICS, NAICS$Location.Type == "Headquarters")

NC <- subset(NAICS, Headquarter$North_Carolina >= 1)
# 88 North Carolina, 713 Total
# 12.3% of incidents are local

Mass <- subset(NAICS, Headquarter$Massachusetts >= 1)
#383 Mass incidents, 1219 total incidents
# 31.4% of incidents are local

NH <- subset(NAICS, Headquarter$New_Hampshire >= 1)
# 20 NH incidents, 444 total incidents
# 4.5 % of incidents are local


table(Mass$Physical.State)

```

